Lesson 6
IvanTselesh/js-pro-course pull request #7
Opened 2022-09-11 21:12 UTC by IvanTselesh

Добрый день!
В общем, я вроде полностью сделал требуемое задание из 6-ой домашки, кроме стилей страниц подкорреткированных для удобного просмотра и темной темы, потому что мне последнее время не хватает времени на css, но я буду доделывать к среде и, думаю, что успею) Насколько я понимаю, то темную тему интегрировать проще всего, используя оформление контейнера в другой цвет фона, например, а также изменения цветовых схем основных компонентов(кнопки и инпута, включая изменения шрифта), после чего уже в самих компонентах, подвергшихся изменению прописать  условие через тернарник о смене темы на соответствующую?

2022-09-14 14:31 UTC, dromanchuck requested changes
В целом все ок, поправить комменты, 
и доделать темную тему)
И да, отвечаю на вопрос, абсолютно верно понимаешь, так и надо делать)

2022-09-14 14:31 UTC, dromanchuck commented on js-pro-course/src/components/InfoTemplate/InfoTemplate.tsx
> +      <p>text2</p>
этот текст должен приходить пропсом
```jsx
<div>
      <h2>{props.header}</h2>
      <p>{props.text1}</p>
      <p>{props.text2}</p>
....
 ```

2022-09-14 14:31 UTC, dromanchuck commented on js-pro-course/src/components/NavBar/NavBar.tsx
> +              <a>Login</a>
Здесь можно использовать компонент Link, для того чтобы нажатия переключали страницы

2022-09-14 14:31 UTC, dromanchuck commented on js-pro-course/src/components/Pages/FullPost/FullPost.tsx
> +      }
SelectedPost должен отображать инфу об одном посте

2022-09-23 18:02 UTC, IvanTselesh commented
Добрый день!
Исправил проблемы и сделал классную работу 7 тоже в данной ветке. Могу ли мерджить?)

2022-09-28 10:50 UTC, dromanchuck reviewed
Все отлично, можно мержить)

2022-09-28 10:50 UTC, dromanchuck approved these changes

2022-09-28 18:22 UTC, merged